- hosts: etcd
  gather_facts: True
  become: True

- hosts: localhost
  gather_facts: False
  become: False
  tasks:
    - name: "Create ~/etcd-certificates"
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates"
        state: directory

- hosts: localhost
  gather_facts: False
  become: False
  tasks:
    - name: "Generate private key for each member"
      openssl_privatekey:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ item }}.key"
        type: RSA
        size: 4096
        state: present
        force: True
      with_items: "{{ groups['etcd'] }}"
    - name: "Generate CSR for each member"
      openssl_csr:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ item }}.csr"
        privatekey_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ item }}.key"
        common_name: "{{ item }}"
        key_usage:
          - digitalSignature
        extended_key_usage:
          - serverAuth
        subject_alt_name:
          - IP:{{ hostvars[item]['ansible_default_ipv4']['address'] }}
        force: True
      with_items: "{{ groups['etcd'] }}"
    - name: "Generate private key for CA"
      openssl_privatekey:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.key"
        type: RSA
        size: 4096
        state: present
        force: True
    - name: "Generate CSR for CA"
      openssl_csr:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.csr"
        privatekey_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.key"
        common_name: ca
        organization_name: "Etcd CA"
        basic_constraints:
          - CA:TRUE
          - pathlen:1
        basic_constraints_critical: True
        key_usage:
          - keyCertSign
          - digitalSignature
        force: True
    - name: "Generate self-signed CA certificate"
      openssl_certificate:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.crt"
        privatekey_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.key"
        csr_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.csr"
        provider: selfsigned
        force: True
    - name: "Generate an etcd member certificate signed with our own CA certificate"
      openssl_certificate:
        path: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ item }}.crt"
        csr_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ item }}.csr"
        ownca_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.crt"
        ownca_privatekey_path: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.key"
        provider: ownca
        force: True
      with_items: "{{ groups['etcd'] }}"


- hosts: etcd
  tasks:
    - name: "Create directory for etcd configuration"
      file:
        path: "/home/{{ lookup('env', 'USER') }}/etcd-certificates"
        state: directory
        mode: 0755

    - name: "Copy over the CA certificate"
      copy:
        src: "{{ lookup('env', 'HOME') }}/etcd-certificates/ca.crt"
        remote_src: False
        dest: "/home/{{ lookup('env', 'USER') }}/etcd-certificates/ca.crt"
        mode: 0644

    - name: "Copy over the etcd member certificate"
      copy:
        src: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ inventory_hostname }}.crt"
        remote_src: False
        dest: "/home/{{ lookup('env', 'USER') }}/etcd-certificates/server.crt"
        mode: 0644

    - name: "Copy over the etcd member key"
      copy:
        src: "{{ lookup('env', 'HOME') }}/etcd-certificates/{{ inventory_hostname }}.key"
        remote_src: False
        dest: "/home/{{ lookup('env', 'USER') }}/etcd-certificates/server.key"
        mode: 0600
