require('strict').on()

local CONSTANT = {}

CONSTANT.ACTIVE = 1
CONSTANT.INACTIVE = 0

CONSTANT.STATUS_OK                  = 'OK'
CONSTANT.STATUS_NOT_FOUND           = 'NOT_FOUND'

CONSTANT.STATUS_UNDEFINED_ID        = 'UNDEFINED_ID'
CONSTANT.STATUS_UNDEFINED_IP        = 'UNDEFINED_IP'
CONSTANT.STATUS_UNDEFINED_IP_FROM   = 'UNDEFINED_IP_FROM'
CONSTANT.STATUS_UNDEFINED_IP_TO     = 'UNDEFINED_IP_TO'
CONSTANT.STATUS_UNDEFINED_IS_ACTIVE = 'UNDEFINED_IS_ACTIVE'
CONSTANT.STATUS_UNDEFINED_COMMENT   = 'UNDEFINED_COMMENT'
CONSTANT.STATUS_UNDEFINED_NETWORK   = 'UNDEFINED_NETWORK'

CONSTANT.STATUS_INVALID_ID        = 'INVALID_ID'
CONSTANT.STATUS_INVALID_IP        = 'INVALID_IP'
CONSTANT.STATUS_INVALID_IP_FROM   = 'INVALID_IP_FROM'
CONSTANT.STATUS_INVALID_IP_TO     = 'INVALID_IP_TO'
CONSTANT.STATUS_INVALID_IS_ACTIVE = 'INVALID_IS_ACTIVE'
CONSTANT.STATUS_UNDEFINED_LIMIT   = 'UNDEFINED_LIMIT'
CONSTANT.STATUS_INVALID_LIMIT     = 'INVALID_LIMIT'
CONSTANT.STATUS_INVALID_NETWORK   = 'INVALID_NETWORK'

return CONSTANT